### ISSUE TITLE
Not able to clone the gitlab repo

### ISSUE THREAD

**Issue by nehas510** [christian-bromann/appium-hbbtv-driver#1]
HI,
I was following all the steps mentioned in the README and tried to clone the repo from gitlab. Please note I have also uploaded my ssh key still it asks for the password.

Thanks in advance for the help.
Neha

**Comment by christian-bromann** [comment]
@nehas510 do you have a a log or an image of the error?

**Comment by nehas510** [comment]
<img width="839" alt="screen shot 2018-01-31 at 3 06 23 pm" src="https://user-images.githubusercontent.com/20065178/35619766-7bd1877a-0698-11e8-87b0-cb86628ca440.png">

**Comment by nehas510** [comment]
is it Ok if I clone this repo from github?

**Comment by nehas510** [comment]
is it OK if I cloned it from GitHub....I mean are both of them same or is there any difference?

**Comment by christian-bromann** [comment]
@nehas510 yes, please clone from GitHub
