### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by aleksanterisaarela** [christian-bromann/appium-hbbtv-driver#11]
Is this repository still maintained? Tried to get it to work but seems to be failing, just like travis-ci indicates as well.

**Comment by christian-bromann** [comment]
Hey @aleksanterisaarela,

sorry but I haven't had the time to continue working on this repo. I am happy to give you push rights though if you want to make changes.

**Comment by aleksanterisaarela** [comment]
Thanks for the quick reply @christian-bromann,

Push rights would be nice, maybe I'll find the time to work and contribute on this one day :)

**Comment by christian-bromann** [comment]
Just assigned you push rights

**Comment by aleksanterisaarela** [comment]
Thanks!
