### ISSUE TITLE
Getting an error after starting the server 

### ISSUE THREAD

**Issue by nehas510** [christian-bromann/appium-hbbtv-driver#2]
> appium-hbbtv-driver@0.0.0 start /home/pi/appium-hbbtv-driver
> npm run start:server

> appium-hbbtv-driver@0.0.0 start:server /home/pi/appium-hbbtv-driver
> node build/index.js

Error: Cannot find module 'devtools-backend'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/appium-hbbtv-driver/build/driver.js:72:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/appium-hbbtv-driver/build/index.js:43:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v7.8.0/bin/node" "/home/pi/.nvm/versions/node/v7.8.0/bin/npm" "run" "start:server"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-hbbtv-driver@0.0.0 start:server: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-hbbtv-driver@0.0.0 start:server script 'node build/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-hbbtv-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-hbbtv-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-hbbtv-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2018-01-29T11_14_01_394Z-debug.log

npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v7.8.0/bin/node" "/home/pi/.nvm/versions/node/v7.8.0/bin/npm" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-hbbtv-driver@0.0.0 start: `npm run start:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-hbbtv-driver@0.0.0 start script 'npm run start:server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-hbbtv-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run start:server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-hbbtv-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-hbbtv-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2018-01-29T11_14_01_499Z-debug.log

**Comment by christian-bromann** [comment]
You need to build and link [this](https://github.com/christian-bromann/devtools-backend) into the node_modules directory to get it working. After I was working on this I didn't published the stuff to NPM.

**Comment by nehas510** [comment]
Thanks, @christian-bromann  I will try this and update you!

Thanks again 
Neha

**Comment by nehas510** [comment]
This did the trick Thanks @christian-bromann

**Comment by christian-bromann** [comment]
Awesome 👍

**Comment by christian-bromann** [comment]
FYI: I don't have the time to work actively on this. If you want I can give you access rights so you can publish the packages to NPM and fix the actual issue.

**Comment by nehas510** [comment]
Sure will be glad to contribute to it.

Thanks,
Neha

*Best Regards*,
*Neha Shah*

**Comment by christian-bromann** [comment]
@nehas510 added you to devtools-backend and appium-hbbtv-driver

**Comment by nehas510** [comment]
thnx @christian-bromann
