### ISSUE TITLE
Not able to share the network of Pi to the TV

### ISSUE THREAD

**Issue by nehas510** [christian-bromann/appium-hbbtv-driver#3]
HI Christian,

I am trying to set up the PI and connected it via the Ethernet to the smart TV. But I am not sure how to share the internet of PI to the Smart Tv so that PI acts as a proxy server.

Thanks,
Neha

**Comment by christian-bromann** [comment]
Hey @nehas510,
did you follow [this](https://github.com/christian-bromann/appium-hbbtv-driver/blob/master/docs/network.md#network-setup) doc? It should explain how to connect the raspberry pi so that it has internet connection and is connected to the TV at the same time.

**Comment by nehas510** [comment]
HI @christian-bromann ,

I tried that but after I reboot PI the WIFI doesn't seems to be connected.

**Comment by nehas510** [comment]
Actually, after I follow all the steps and after the reboot it is not recognizing eth0

**Comment by nehas510** [comment]
After Removing this iface eth0 inet manual it worked for me.

Thanks,
Neha
