### ISSUE TITLE
Do you have any sample test cases available to see if the automation works on my app

### ISSUE THREAD

**Issue by nehas510** [christian-bromann/appium-hbbtv-driver#4]
Hi @christian-bromann,
I have done the setup successfully. Here are the logs which I get after starting the server.(PFA the screenshot). Do you have any document on how to run the sample tests to automate?
<img width="855" alt="screen shot 2018-03-08 at 3 35 36 pm" src="https://user-images.githubusercontent.com/20065178/37149457-76d828f8-22e7-11e8-94e4-10d74de357a3.png">

**Comment by christian-bromann** [comment]
@nehas510 that's awesome! Please make a PR if anything in the docs was unclear.

You can use this project: https://github.com/christian-bromann/sauce-hbbtv-app to start testing your app. It uses WebdriverIO but you can use any other library or language that can speak the WebDriver protocol.

**Comment by nehas510** [comment]
@christian-bromann  Sure I will do that.
Thanks for the project and I will try this and update you.

Thanks a lot for the awesome work :)

**Comment by nehas510** [comment]
Hi @christian-bromann,
I went through the project you shared but I am a bit confused on where should I run the tests and how and where can I specify the name of my Samsung Tv app to launch it?

Thanks,
Neha
