### ISSUE TITLE
Using wifi and eth0 and not eth1 and eth0

### ISSUE THREAD

**Issue by guillemhs** [christian-bromann/appium-hbbtv-driver#8]
Hi,

I think I have a network problem.

I was trying the setup on a Raspi 3, using wlan0 and eth0. Basically both integrated network interfaces.

Checking your docs [here](https://github.com/christian-bromann/appium-hbbtv-driver/blob/master/docs/network.md), it says you used a USB Ethernet adapter.

Is possible to use wlan0 and eth0, or is it mandatory to use eth0 and eth1 on a wired connection?

Best regards,

**Comment by christian-bromann** [comment]
You can definitely also use the Wifi module, you just need to setup the network config.
